### ISSUE TITLE
Maybe I misunderstand the defination of g_loss?

### ISSUE THREAD

**Issue by ShawnPi233** [sumuzhao/CycleGAN-Music-Style-Transfer-Refactorization#16]
In my views, cycle_loss should be a non-negative L1 norm result, and it should be small. But I find in your code `tf2_model.py` , `g_loss = g_A2B_loss + g_B2A_loss - cycle_loss`, maybe it should be `g_loss = g_A2B_loss + g_B2A_loss + cycle_loss`

Hopefully, I can get some help, thanks.

**Comment by Asthestarsfalll** [comment]
`g_A2B_loss` and `g_B2A_loss` both contain `cycle_loss`, so it need to subtract a `cycle_loss`

**Comment by ShawnPi233** [comment]
> `g_A2B_loss` and `g_B2A_loss` both contain `cycle_loss`, so it need to subtract a `cycle_loss`

Thanks a lot, I have got it.
